### ISSUE TITLE
Gnome 45 support?

### ISSUE THREAD

**Issue by debianmain1** [Gniourf/Uptime-Indicator#20]
Just wondering if you will be supporting Gnome 45?  Thanks!

**Comment by Gniourf** [comment]
Hi @debianmain1, yes of course I will!

I just merged @gilvbp  's branch, and I sent it to gnome's extension website. I just got a reply from them, and I need to fix a couple of minor things before they publish it. I'm in the process of fixing these, so it should be ready shortly!

**Comment by debianmain1** [comment]
Thank You!!!!!

**Comment by galen1423** [comment]
Thanks for updating this extension for GS 45. :+1: 

Regards
