### ISSUE TITLE
This is a good extension!

### ISSUE THREAD

**Issue by mudongliang** [Gniourf/Uptime-Indicator#4]
This is a good extension , I like it !
It solves my problem , I don't need to exec "uptime " whenever I want to know the time !
Thank you !

**Comment by Gniourf** [comment]
Please don't use this space for comments; this space is meant for issues, bugs, etc. To leave a comment, please use the [Uptime Indicator extension page](https://extensions.gnome.org/extension/508/uptime-indicator/) (and give a 5-stars rating there!). Thanks anyway `:)`.
